# Generated by Django 5.2.16 on 2026-09-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthyAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product or whole food name (e.g. 100% Roasted Peanut Butter)', max_length=200)),
                ('brand', models.CharField(blank=True, default='Clean Whole Foods', max_length=100)),
                ('category', models.CharField(choices=[('chocolate_spread', 'Chocolate & Sweet Spreads'), ('soda_cola', 'Sodas & Carbonated Soft Drinks'), ('potato_chips', 'Fried Chips & Crisps'), ('instant_noodles', 'Instant Noodles & Ramen'), ('sweet_biscuits', 'Biscuits & Cookies'), ('fruit_juice_sweetened', 'Packaged Juices & Sugary Drinks'), ('default_clean', 'General Clean Whole Foods')], default='chocolate_spread', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Display image URL', max_length=500, null=True)),
                ('normalized_score', models.FloatField(default=15.0, help_text='Health Risk Score (0-100, lower is better)')),
                ('risk_label', models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate')], default='Low', max_length=20)),
                ('why_better', models.TextField(help_text='Clinical or dietary explanation of why it is healthier')),
                ('energy_kcal', models.FloatField(default=0.0, verbose_name='Calories (kcal)')),
                ('sugars', models.FloatField(default=0.0, verbose_name='Sugars (g)')),
                ('proteins', models.FloatField(default=0.0, verbose_name='Proteins (g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='Fat (g)')),
                ('saturated_fat', models.FloatField(default=0.0, verbose_name='Saturated Fat (g)')),
                ('salt', models.FloatField(default=0.0, verbose_name='Salt (g)')),
                ('fiber', models.FloatField(default=0.0, verbose_name='Fiber (g)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='Carbohydrates (g)')),
                ('allergens', models.CharField(blank=True, help_text='Comma-separated allergens (e.g. peanuts, gluten, dairy, soy, tree nuts)', max_length=255)),
                ('avoid_for_conditions', models.CharField(blank=True, help_text='Comma-separated health conditions that should avoid this (e.g. Diabetes, Hypertension)', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alternative is active in recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Healthy Alternative Product',
                'verbose_name_plural': 'Healthy Alternative Products',
                'ordering': ['normalized_score', 'name'],
            },
        ),
    ]
