# Generated by Django 5.2.16 on 2026-08-17 07:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Canonical ingredient name (e.g., "Sodium Benzoate")', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('sweetener', 'Sweetener'), ('preservative', 'Preservative'), ('fat', 'Fat / Oil'), ('flavor_enhancer', 'Flavor Enhancer'), ('sodium_containing', 'Sodium-Containing'), ('refined_carb', 'Refined Carbohydrate'), ('natural', 'Natural / Low-Risk'), ('emulsifier', 'Emulsifier'), ('colorant', 'Colorant'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('base_risk_score', models.DecimalField(decimal_places=2, help_text='Base risk score from 0 (safe) to 10 (high risk)', max_digits=4, validators=[django.core.validators.MinValueValidator(0, message='Score must be at least 0.'), django.core.validators.MaxValueValidator(10, message='Score must be at most 10.')])),
                ('allergen_flag', models.BooleanField(default=False, help_text='True if this ingredient is a common allergen')),
                ('source_reference', models.TextField(blank=True, default='', help_text='Citation / source for the risk score assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConditionMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(db_index=True, help_text='Health condition name, must match HealthCondition.condition_name', max_length=100)),
                ('ingredient_category', models.CharField(choices=[('sweetener', 'Sweetener'), ('preservative', 'Preservative'), ('fat', 'Fat / Oil'), ('flavor_enhancer', 'Flavor Enhancer'), ('sodium_containing', 'Sodium-Containing'), ('refined_carb', 'Refined Carbohydrate'), ('natural', 'Natural / Low-Risk'), ('emulsifier', 'Emulsifier'), ('colorant', 'Colorant'), ('other', 'Other')], db_index=True, help_text='Ingredient category this rule applies to', max_length=30)),
                ('multiplier_value', models.DecimalField(decimal_places=2, help_text='Multiplier applied to base_risk_score (e.g., 1.5 = 50% increase)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.1, message='Multiplier must be at least 0.1.')])),
            ],
            options={
                'ordering': ['condition_name', 'ingredient_category'],
                'unique_together': {('condition_name', 'ingredient_category')},
            },
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_name', models.CharField(help_text='Alternate name or E-number', max_length=200, unique=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='scoring.ingredient')),
            ],
            options={
                'verbose_name_plural': 'Ingredient aliases',
                'ordering': ['alias_name'],
            },
        ),
    ]
