# Generated by Django 5.2.16 on 2026-08-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthcondition_severity'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoredResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.DecimalField(decimal_places=4, help_text='Sum of all ingredient_impact values before normalization', max_digits=8)),
                ('normalized_score', models.DecimalField(decimal_places=2, help_text='Final score normalized to 0-100', max_digits=6)),
                ('has_allergen_warning', models.BooleanField(default=False, help_text='True if any matched ingredient triggers an allergen warning')),
                ('allergen_details', models.JSONField(blank=True, default=list, help_text='List of allergen names that triggered warnings')),
                ('risk_label', models.CharField(blank=True, default='', help_text='Human-readable risk label: Low / Moderate / High', max_length=20)),
                ('ingredients_text', models.TextField(blank=True, default='', help_text='Original raw ingredients text that was scored')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_results', to='health.healthprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoredIngredientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_token', models.CharField(help_text='Original token from the ingredients list', max_length=200)),
                ('position', models.PositiveIntegerField(help_text='1-indexed position in the ingredients list')),
                ('base_risk_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('adjusted_score', models.DecimalField(decimal_places=2, default=0, help_text='Score after condition multiplier + severity weighting', max_digits=5)),
                ('position_weight', models.DecimalField(decimal_places=4, default=0, help_text='1 / position', max_digits=6)),
                ('ingredient_impact', models.DecimalField(decimal_places=4, default=0, help_text='adjusted_score * position_weight', max_digits=8)),
                ('is_allergen_trigger', models.BooleanField(default=False, help_text='True if this ingredient triggered an allergen warning')),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scoring.ingredient')),
                ('scored_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_details', to='scoring.scoredresult')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
