# Generated by Django 5.2.16 on 2026-08-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scoredresult_scoredingredientdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredresult',
            name='barcode',
            field=models.CharField(blank=True, default='', help_text='Barcode of the scanned product (for history display)', max_length=50),
        ),
        migrations.AddField(
            model_name='scoredresult',
            name='product_image_url',
            field=models.URLField(blank=True, default='', help_text='Product image URL at time of scan', max_length=500),
        ),
        migrations.AddField(
            model_name='scoredresult',
            name='product_name',
            field=models.CharField(blank=True, default='', help_text='Product name at time of scan', max_length=300),
        ),
    ]
