# Generated by Django 5.2.16 on 2026-08-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_scoredresult_barcode_scoredresult_product_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredresult',
            name='nutrition_data',
            field=models.JSONField(blank=True, default=dict, help_text='Nutritional values per 100g at time of scan: energy_kcal, fat, sugars, proteins, salt, fiber, carbohydrates'),
        ),
    ]
