# Generated by Django 5.2.16 on 2026-09-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_scoredresult_nutrition_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of the product (required)', max_length=300)),
                ('brand', models.CharField(blank=True, default='', help_text='Brand or manufacturer name', max_length=200)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', help_text='Barcode (EAN-13/UPC) if available', max_length=50)),
                ('ingredients_text', models.TextField(help_text='Raw ingredients text as printed on the label')),
                ('nutrition_data', models.JSONField(blank=True, default=dict, help_text='Optional nutrition info: {energy_kcal, fat, sugars, salt}')),
                ('notes', models.TextField(blank=True, default='', help_text='Any additional notes from the submitter')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Admin notes (e.g. reason for rejection)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='User who submitted this product', on_delete=django.db.models.deletion.CASCADE, related_name='community_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
