# Generated by Django 5.2.16 on 2026-09-28 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_communitysubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalorieGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_goal_kcal', models.PositiveIntegerField(default=2000, help_text='User-defined daily calorie intake goal in kcal', validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(10000)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calorie_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualFoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(help_text='Name of the food item', max_length=300)),
                ('calories_kcal', models.DecimalField(decimal_places=2, help_text='Estimated calories in kcal for the given serving', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('serving_description', models.CharField(blank=True, default='', help_text='e.g. "1 cup", "100g", "1 plate"', max_length=200)),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('photo', 'Photo Analysis')], default='manual', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('logged_at', models.DateField(help_text='Date of consumption (defaults to today)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_food_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
