# Generated by Django 5.2.16 on 2026-08-28 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scoring', '0002_scoredresult_scoredingredientdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_text', models.TextField(help_text='The LLM-generated plain-language explanation')),
                ('llm_model_used', models.CharField(help_text='LLM model identifier for auditability (e.g., "gemini-2.0-flash")', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this explanation was generated')),
                ('scored_result', models.OneToOneField(help_text='The scored result this explanation describes (one-to-one)', on_delete=django.db.models.deletion.CASCADE, related_name='explanation', to='scoring.scoredresult')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExplanationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True = thumbs up, False = thumbs down')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this feedback was submitted')),
                ('explanation', models.ForeignKey(help_text='The explanation this feedback is for', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='explanations.explanation')),
                ('user', models.ForeignKey(help_text='The user who submitted this feedback', on_delete=django.db.models.deletion.CASCADE, related_name='explanation_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('explanation', 'user')},
            },
        ),
    ]
